#ifndef DATAENGUIAMOBILE_H
#define DATAENGUIAMOBILE_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include <QList>
#include <QVariant>
#include "edistinctmsguser.h"
#include "efunpicture.h"
#include "efunplace.h"
#include "ecsfunplacecomment.h"
#include "ecsmessage.h"
#include "ecsnew.h"
#include "ecsnewcomment.h"
#include "ecsnewlike.h"
#include "enewgrouped.h"
#include "erating.h"
#include "eimage.h"
#include "econtact.h"
#include "econtactsgroup.h"
#include "econtactsgroupuser.h"
#include "eadscategory.h"
#include "eappconfig.h"
#include "efavorite.h"
#include "euserhistory.h"
#include "efunplacescomment.h"
#include "efunview.h"
#include "eicon.h"
#include "eneighborhood.h"
#include "enewscomment.h"
#include "enewslike.h"
#include "ecategory.h"
#include "emobilecounts.h"
#include "erblockschedule.h"
#include "esqliteconfig.h"
#include "euserblock.h"
#include "euserblockwelcome.h"
#include "euserblockmenu.h"
#include "eusermenu.h"
#include "euserblockpictures.h"
#include "euserpicture.h"
#include "euserblockproducts.h"
#include "euserproduct.h"
#include "euserorderconfirmation.h"
#include "euserproductcategory.h"
#include "euserproductoption.h"
#include "euserproductaddon.h"
#include "euserblockschedule.h"
#include "euserblocktext.h"
#include "esearch.h"
#include "euserfavorite.h"
#include "euserservice.h"
#include "euserservicetimetablestatus.h"
#include "euserservicetimetable.h"
#include "euserserviceexception.h"
#include "euserschedule.h"
#include "euserscheduleconfirmation.h"
#include "euserclient.h"
#include "euserschedulequeue.h"
#include "etest.h"


class DATAENGUIAMOBILE{
public:
	static QList<QMetaObject> getMeta() {
		return QList<QMetaObject>() 
			<<EDistinctMsgUser::getMeta()
			<<EFunPicture::getMeta()
			<<EFunPlace::getMeta()
			<<ECSFunPlaceComment::getMeta()
			<<ECSMessage::getMeta()
			<<ECSNew::getMeta()
			<<ECSNewComment::getMeta()
			<<ECSNewLike::getMeta()
			<<ENewGrouped::getMeta()
			<<ERating::getMeta()
			<<EImage::getMeta()
			<<EContact::getMeta()
			<<EContactsGroup::getMeta()
			<<EContactsGroupUser::getMeta()
			<<EAdsCategory::getMeta()
			<<EAppConfig::getMeta()
			<<EFavorite::getMeta()
			<<EUserHistory::getMeta()
			<<EFunPlacesComment::getMeta()
			<<EFunView::getMeta()
			<<EIcon::getMeta()
			<<ENeighborhood::getMeta()
			<<ENewsComment::getMeta()
			<<ENewsLike::getMeta()
			<<ECategory::getMeta()
			<<EMobileCounts::getMeta()
			<<ERBlockSchedule::getMeta()
			<<ESqliteConfig::getMeta()
			<<EUserBlock::getMeta()
			<<EUserBlockWelcome::getMeta()
			<<EUserBlockMenu::getMeta()
			<<EUserMenu::getMeta()
			<<EUserBlockPictures::getMeta()
			<<EUserPicture::getMeta()
			<<EUserBlockProducts::getMeta()
			<<EUserProduct::getMeta()
			<<EUserOrderConfirmation::getMeta()
			<<EUserProductCategory::getMeta()
			<<EUserProductOption::getMeta()
			<<EUserProductAddon::getMeta()
			<<EUserBlockSchedule::getMeta()
			<<EUserBlockText::getMeta()
			<<ESearch::getMeta()
			<<EUserFavorite::getMeta()
			<<EUserService::getMeta()
			<<EUserServiceTimetableStatus::getMeta()
			<<EUserServiceTimetable::getMeta()
			<<EUserServiceException::getMeta()
			<<EUserSchedule::getMeta()
			<<EUserScheduleConfirmation::getMeta()
			<<EUserClient::getMeta()
			<<EUserScheduleQueue::getMeta()
			<<ETest::getMeta();
	}
};
#endif
