#ifndef ECSFUNPLACECOMMENT_H
#define ECSFUNPLACECOMMENT_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include "QStringList"
#include "QDateTime"
#include "QVariant"
#include "QObject"


/**
*@class ECSFunPlaceComment
**/
class  ECSFunPlaceComment : public QObject {
	Q_OBJECT
	Q_PROPERTY(qint64 id READ getId WRITE setId USER true)
	Q_PROPERTY(qint64 funID READ getFunID WRITE setFunID USER true)
	Q_PROPERTY(qint64 userID READ getUserID WRITE setUserID USER true)
	Q_PROPERTY(qint32 rating READ getRating WRITE setRating USER true)
	Q_PROPERTY(qint64 categoryID READ getCategoryID WRITE setCategoryID USER true)
	Q_PROPERTY(QString funName READ getFunName WRITE setFunName USER true)
	Q_PROPERTY(QString comment READ getComment WRITE setComment USER true)
	Q_PROPERTY(QDate dateInserted READ getDateInserted WRITE setDateInserted USER true)
	Q_PROPERTY(QString userName READ getUserName WRITE setUserName USER true)
	Q_PROPERTY(QString login READ getLogin WRITE setLogin USER true)

public:
	Q_INVOKABLE ECSFunPlaceComment(QObject *parent=0);
	~ECSFunPlaceComment(){}
	static QMetaObject getMeta();
	Q_INVOKABLE ECSFunPlaceComment(const ECSFunPlaceComment &d) : QObject () { setData(d); }
	Q_INVOKABLE ECSFunPlaceComment &operator=(const ECSFunPlaceComment &d){ return setData(d); }
	Q_INVOKABLE bool operator== (const ECSFunPlaceComment &other) const{ if(equal(other))return true;return false;}
	Q_INVOKABLE inline bool operator!= (const ECSFunPlaceComment &other) const{ if(equal(other))return false;return true;}
	inline qint64 getId() const {return id;}
	void setId(qint64 d){id=d;}
	inline qint64 getFunID() const {return funID;}
	void setFunID(qint64 d){funID=d;}
	inline qint64 getUserID() const {return userID;}
	void setUserID(qint64 d){userID=d;}
	inline qint32 getRating() const {return rating;}
	void setRating(qint32 d){rating=d;}
	inline qint64 getCategoryID() const {return categoryID;}
	void setCategoryID(qint64 d){categoryID=d;}
	Q_INVOKABLE QString getFunName() const {return funName;}
	void setFunName(const QString &d){funName=d;}
	Q_INVOKABLE QString getComment() const {return comment;}
	void setComment(const QString &d){comment=d;}
	Q_INVOKABLE QDate getDateInserted() const {return dateInserted;}
	void setDateInserted(const QDate &d){dateInserted=d;}
	Q_INVOKABLE QString getUserName() const {return userName;}
	void setUserName(const QString &d){userName=d;}
	Q_INVOKABLE QString getLogin() const {return login;}
	void setLogin(const QString &d){login=d;}

protected:
	ECSFunPlaceComment &setData(const ECSFunPlaceComment &d){
		id=d.id;
		funID=d.funID;
		userID=d.userID;
		rating=d.rating;
		categoryID=d.categoryID;
		funName=d.funName;
		comment=d.comment;
		dateInserted=d.dateInserted;
		userName=d.userName;
		login=d.login;
		return *this;
	}
	bool equal(const ECSFunPlaceComment &other) const {
		if(id!=other.id)return false;
		if(funID!=other.funID)return false;
		if(userID!=other.userID)return false;
		if(rating!=other.rating)return false;
		if(categoryID!=other.categoryID)return false;
		if(funName!=other.funName)return false;
		if(comment!=other.comment)return false;
		if(dateInserted!=other.dateInserted)return false;
		if(userName!=other.userName)return false;
		if(login!=other.login)return false;
		return true;
	}
	qint64 id;
	qint64 funID;
	qint64 userID;
	qint32 rating;
	qint64 categoryID;
	QString funName;
	QString comment;
	QDate dateInserted;
	QString userName;
	QString login;
};

Q_DECLARE_METATYPE(ECSFunPlaceComment)
Q_DECLARE_METATYPE(ECSFunPlaceComment*)
Q_DECLARE_METATYPE(QList<ECSFunPlaceComment*>)
Q_DECLARE_METATYPE(QList<ECSFunPlaceComment>)
#endif
