#ifndef ECSNEWCOMMENT_H
#define ECSNEWCOMMENT_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include "QStringList"
#include "QDateTime"
#include "QVariant"
#include "QObject"


/**
*@class ECSNewComment
**/
class  ECSNewComment : public QObject {
	Q_OBJECT
	Q_PROPERTY(qint64 id READ getId WRITE setId USER true)
	Q_PROPERTY(qint64 newsID READ getNewsID WRITE setNewsID USER true)
	Q_PROPERTY(qint64 userID READ getUserID WRITE setUserID USER true)
	Q_PROPERTY(QString comment READ getComment WRITE setComment USER true)
	Q_PROPERTY(QDateTime dateInserted READ getDateInserted WRITE setDateInserted USER true)
	Q_PROPERTY(QString userName READ getUserName WRITE setUserName USER true)
	Q_PROPERTY(QString login READ getLogin WRITE setLogin USER true)
	Q_PROPERTY(QByteArray userIcon READ getUserIcon WRITE setUserIcon USER true)

public:
	Q_INVOKABLE ECSNewComment(QObject *parent=0);
	~ECSNewComment(){}
	static QMetaObject getMeta();
	Q_INVOKABLE ECSNewComment(const ECSNewComment &d) : QObject () { setData(d); }
	Q_INVOKABLE ECSNewComment &operator=(const ECSNewComment &d){ return setData(d); }
	Q_INVOKABLE bool operator== (const ECSNewComment &other) const{ if(equal(other))return true;return false;}
	Q_INVOKABLE inline bool operator!= (const ECSNewComment &other) const{ if(equal(other))return false;return true;}
	inline qint64 getId() const {return id;}
	void setId(qint64 d){id=d;}
	inline qint64 getNewsID() const {return newsID;}
	void setNewsID(qint64 d){newsID=d;}
	inline qint64 getUserID() const {return userID;}
	void setUserID(qint64 d){userID=d;}
	Q_INVOKABLE QString getComment() const {return comment;}
	void setComment(const QString &d){comment=d;}
	Q_INVOKABLE QDateTime getDateInserted() const {return dateInserted;}
	void setDateInserted(const QDateTime &d){dateInserted=d;}
	Q_INVOKABLE QString getUserName() const {return userName;}
	void setUserName(const QString &d){userName=d;}
	Q_INVOKABLE QString getLogin() const {return login;}
	void setLogin(const QString &d){login=d;}
	Q_INVOKABLE QByteArray getUserIcon() const {return userIcon;}
	void setUserIcon(const QByteArray &d){userIcon=d;}

protected:
	ECSNewComment &setData(const ECSNewComment &d){
		id=d.id;
		newsID=d.newsID;
		userID=d.userID;
		comment=d.comment;
		dateInserted=d.dateInserted;
		userName=d.userName;
		login=d.login;
		userIcon=d.userIcon;
		return *this;
	}
	bool equal(const ECSNewComment &other) const {
		if(id!=other.id)return false;
		if(newsID!=other.newsID)return false;
		if(userID!=other.userID)return false;
		if(comment!=other.comment)return false;
		if(dateInserted!=other.dateInserted)return false;
		if(userName!=other.userName)return false;
		if(login!=other.login)return false;
		if(userIcon!=other.userIcon)return false;
		return true;
	}
	qint64 id;
	qint64 newsID;
	qint64 userID;
	QString comment;
	QDateTime dateInserted;
	QString userName;
	QString login;
	QByteArray userIcon;
};

Q_DECLARE_METATYPE(ECSNewComment)
Q_DECLARE_METATYPE(ECSNewComment*)
Q_DECLARE_METATYPE(QList<ECSNewComment*>)
Q_DECLARE_METATYPE(QList<ECSNewComment>)
#endif
