#ifndef EDISTINCTMSGUSER_H
#define EDISTINCTMSGUSER_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include "QStringList"
#include "QDateTime"
#include "QVariant"
#include "QObject"


/**
*@class EDistinctMsgUser
**/
class  EDistinctMsgUser : public QObject {
	Q_OBJECT
	Q_PROPERTY(qint64 userID READ getUserID WRITE setUserID USER true)
	Q_PROPERTY(QString userName READ getUserName WRITE setUserName USER true)
	Q_PROPERTY(QString login READ getLogin WRITE setLogin USER true)
	Q_PROPERTY(qint64 msgID READ getMsgID WRITE setMsgID USER true)

public:
	Q_INVOKABLE EDistinctMsgUser(QObject *parent=0);
	~EDistinctMsgUser(){}
	static QMetaObject getMeta();
	Q_INVOKABLE EDistinctMsgUser(const EDistinctMsgUser &d) : QObject () { setData(d); }
	Q_INVOKABLE EDistinctMsgUser &operator=(const EDistinctMsgUser &d){ return setData(d); }
	Q_INVOKABLE bool operator== (const EDistinctMsgUser &other) const{ if(equal(other))return true;return false;}
	Q_INVOKABLE inline bool operator!= (const EDistinctMsgUser &other) const{ if(equal(other))return false;return true;}
	inline qint64 getUserID() const {return userID;}
	void setUserID(qint64 d){userID=d;}
	Q_INVOKABLE QString getUserName() const {return userName;}
	void setUserName(const QString &d){userName=d;}
	Q_INVOKABLE QString getLogin() const {return login;}
	void setLogin(const QString &d){login=d;}
	inline qint64 getMsgID() const {return msgID;}
	void setMsgID(qint64 d){msgID=d;}

protected:
	EDistinctMsgUser &setData(const EDistinctMsgUser &d){
		userID=d.userID;
		userName=d.userName;
		login=d.login;
		msgID=d.msgID;
		return *this;
	}
	bool equal(const EDistinctMsgUser &other) const {
		if(userID!=other.userID)return false;
		if(userName!=other.userName)return false;
		if(login!=other.login)return false;
		if(msgID!=other.msgID)return false;
		return true;
	}
	qint64 userID;
	QString userName;
	QString login;
	qint64 msgID;
};

Q_DECLARE_METATYPE(EDistinctMsgUser)
Q_DECLARE_METATYPE(EDistinctMsgUser*)
Q_DECLARE_METATYPE(QList<EDistinctMsgUser*>)
Q_DECLARE_METATYPE(QList<EDistinctMsgUser>)
#endif
