#ifndef EFAVORITE_H
#define EFAVORITE_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include "QStringList"
#include "QDateTime"
#include "QVariant"
#include "QObject"


/**
*@class EFavorite
**/
class  EFavorite : public QObject {
	Q_OBJECT
	Q_PROPERTY(qint64 id READ getId WRITE setId USER true)
	Q_PROPERTY(qint64 userID READ getUserID WRITE setUserID USER true)
	Q_PROPERTY(qint64 placeID READ getPlaceID WRITE setPlaceID USER true)

public:
	Q_INVOKABLE EFavorite(QObject *parent=0);
	~EFavorite(){}
	static QMetaObject getMeta();
	Q_INVOKABLE EFavorite(const EFavorite &d) : QObject () { setData(d); }
	Q_INVOKABLE EFavorite &operator=(const EFavorite &d){ return setData(d); }
	Q_INVOKABLE bool operator== (const EFavorite &other) const{ if(equal(other))return true;return false;}
	Q_INVOKABLE inline bool operator!= (const EFavorite &other) const{ if(equal(other))return false;return true;}
	inline qint64 getId() const {return id;}
	void setId(qint64 d){id=d;}
	inline qint64 getUserID() const {return userID;}
	void setUserID(qint64 d){userID=d;}
	inline qint64 getPlaceID() const {return placeID;}
	void setPlaceID(qint64 d){placeID=d;}

protected:
	EFavorite &setData(const EFavorite &d){
		id=d.id;
		userID=d.userID;
		placeID=d.placeID;
		return *this;
	}
	bool equal(const EFavorite &other) const {
		if(id!=other.id)return false;
		if(userID!=other.userID)return false;
		if(placeID!=other.placeID)return false;
		return true;
	}
	qint64 id;
	qint64 userID;
	qint64 placeID;
};

Q_DECLARE_METATYPE(EFavorite)
Q_DECLARE_METATYPE(EFavorite*)
Q_DECLARE_METATYPE(QList<EFavorite*>)
Q_DECLARE_METATYPE(QList<EFavorite>)
#endif
