#ifndef EICON_H
#define EICON_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include "QStringList"
#include "QDateTime"
#include "QVariant"
#include "QObject"


/**
*@class EIcon
**/
class  EIcon : public QObject {
	Q_OBJECT
	Q_PROPERTY(qint64 id READ getId WRITE setId USER true)
	Q_PROPERTY(qint64 iconType READ getIconType WRITE setIconType USER true)
	Q_PROPERTY(qint64 typeID READ getTypeID WRITE setTypeID USER true)
	Q_PROPERTY(QString name READ getName WRITE setName USER true)
	Q_PROPERTY(QString description READ getDescription WRITE setDescription USER true)

public:
	Q_INVOKABLE EIcon(QObject *parent=0);
	~EIcon(){}
	static QMetaObject getMeta();
	Q_INVOKABLE EIcon(const EIcon &d) : QObject () { setData(d); }
	Q_INVOKABLE EIcon &operator=(const EIcon &d){ return setData(d); }
	Q_INVOKABLE bool operator== (const EIcon &other) const{ if(equal(other))return true;return false;}
	Q_INVOKABLE inline bool operator!= (const EIcon &other) const{ if(equal(other))return false;return true;}
	inline qint64 getId() const {return id;}
	void setId(qint64 d){id=d;}
	inline qint64 getIconType() const {return iconType;}
	void setIconType(qint64 d){iconType=d;}
	inline qint64 getTypeID() const {return typeID;}
	void setTypeID(qint64 d){typeID=d;}
	Q_INVOKABLE QString getName() const {return name;}
	void setName(const QString &d){name=d;}
	Q_INVOKABLE QString getDescription() const {return description;}
	void setDescription(const QString &d){description=d;}

protected:
	EIcon &setData(const EIcon &d){
		id=d.id;
		iconType=d.iconType;
		typeID=d.typeID;
		name=d.name;
		description=d.description;
		return *this;
	}
	bool equal(const EIcon &other) const {
		if(id!=other.id)return false;
		if(iconType!=other.iconType)return false;
		if(typeID!=other.typeID)return false;
		if(name!=other.name)return false;
		if(description!=other.description)return false;
		return true;
	}
	qint64 id;
	qint64 iconType;
	qint64 typeID;
	QString name;
	QString description;
};

Q_DECLARE_METATYPE(EIcon)
Q_DECLARE_METATYPE(EIcon*)
Q_DECLARE_METATYPE(QList<EIcon*>)
Q_DECLARE_METATYPE(QList<EIcon>)
#endif
