#ifndef ENEIGHBORHOOD_H
#define ENEIGHBORHOOD_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include "QStringList"
#include "QDateTime"
#include "QVariant"
#include "QObject"


/**
*@class ENeighborhood
**/
class  ENeighborhood : public QObject {
	Q_OBJECT
	Q_PROPERTY(qint64 id READ getId WRITE setId USER true)
	Q_PROPERTY(QString name READ getName WRITE setName USER true)
	Q_PROPERTY(qint32 cityRegion READ getCityRegion WRITE setCityRegion USER true)

public:
	Q_INVOKABLE ENeighborhood(QObject *parent=0);
	~ENeighborhood(){}
	static QMetaObject getMeta();
	Q_INVOKABLE ENeighborhood(const ENeighborhood &d) : QObject () { setData(d); }
	Q_INVOKABLE ENeighborhood &operator=(const ENeighborhood &d){ return setData(d); }
	Q_INVOKABLE bool operator== (const ENeighborhood &other) const{ if(equal(other))return true;return false;}
	Q_INVOKABLE inline bool operator!= (const ENeighborhood &other) const{ if(equal(other))return false;return true;}
	inline qint64 getId() const {return id;}
	void setId(qint64 d){id=d;}
	Q_INVOKABLE QString getName() const {return name;}
	void setName(const QString &d){name=d;}
	inline qint32 getCityRegion() const {return cityRegion;}
	void setCityRegion(qint32 d){cityRegion=d;}

protected:
	ENeighborhood &setData(const ENeighborhood &d){
		id=d.id;
		name=d.name;
		cityRegion=d.cityRegion;
		return *this;
	}
	bool equal(const ENeighborhood &other) const {
		if(id!=other.id)return false;
		if(name!=other.name)return false;
		if(cityRegion!=other.cityRegion)return false;
		return true;
	}
	qint64 id;
	QString name;
	qint32 cityRegion;
};

Q_DECLARE_METATYPE(ENeighborhood)
Q_DECLARE_METATYPE(ENeighborhood*)
Q_DECLARE_METATYPE(QList<ENeighborhood*>)
Q_DECLARE_METATYPE(QList<ENeighborhood>)
#endif
