#ifndef ENEWGROUPED_H
#define ENEWGROUPED_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include "QStringList"
#include "QDateTime"
#include "QVariant"
#include "QObject"


/**
*@class ENewGrouped
**/
class  ENewGrouped : public QObject {
	Q_OBJECT
	Q_PROPERTY(qint64 placeID READ getPlaceID WRITE setPlaceID USER true)
	Q_PROPERTY(qint64 contactID READ getContactID WRITE setContactID USER true)
	Q_PROPERTY(QString contactName READ getContactName WRITE setContactName USER true)
	Q_PROPERTY(qint32 unreadCount READ getUnreadCount WRITE setUnreadCount USER true)

public:
	Q_INVOKABLE ENewGrouped(QObject *parent=0);
	~ENewGrouped(){}
	static QMetaObject getMeta();
	Q_INVOKABLE ENewGrouped(const ENewGrouped &d) : QObject () { setData(d); }
	Q_INVOKABLE ENewGrouped &operator=(const ENewGrouped &d){ return setData(d); }
	Q_INVOKABLE bool operator== (const ENewGrouped &other) const{ if(equal(other))return true;return false;}
	Q_INVOKABLE inline bool operator!= (const ENewGrouped &other) const{ if(equal(other))return false;return true;}
	inline qint64 getPlaceID() const {return placeID;}
	void setPlaceID(qint64 d){placeID=d;}
	inline qint64 getContactID() const {return contactID;}
	void setContactID(qint64 d){contactID=d;}
	Q_INVOKABLE QString getContactName() const {return contactName;}
	void setContactName(const QString &d){contactName=d;}
	inline qint32 getUnreadCount() const {return unreadCount;}
	void setUnreadCount(qint32 d){unreadCount=d;}

protected:
	ENewGrouped &setData(const ENewGrouped &d){
		placeID=d.placeID;
		contactID=d.contactID;
		contactName=d.contactName;
		unreadCount=d.unreadCount;
		return *this;
	}
	bool equal(const ENewGrouped &other) const {
		if(placeID!=other.placeID)return false;
		if(contactID!=other.contactID)return false;
		if(contactName!=other.contactName)return false;
		if(unreadCount!=other.unreadCount)return false;
		return true;
	}
	qint64 placeID;
	qint64 contactID;
	QString contactName;
	qint32 unreadCount;
};

Q_DECLARE_METATYPE(ENewGrouped)
Q_DECLARE_METATYPE(ENewGrouped*)
Q_DECLARE_METATYPE(QList<ENewGrouped*>)
Q_DECLARE_METATYPE(QList<ENewGrouped>)
#endif
