#ifndef EUSERBLOCKPICTURES_H
#define EUSERBLOCKPICTURES_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include "QStringList"
#include "QDateTime"
#include "QVariant"
#include "QObject"


/**
*@class EUserBlockPictures
**/
class  EUserBlockPictures : public QObject {
	Q_OBJECT
	Q_PROPERTY(qint64 id READ getId WRITE setId USER true)
	Q_PROPERTY(qint64 userID READ getUserID WRITE setUserID USER true)
	Q_PROPERTY(QString name READ getName WRITE setName USER true)
	Q_PROPERTY(qint32 visibility READ getVisibility WRITE setVisibility USER true)

public:
	Q_INVOKABLE EUserBlockPictures(QObject *parent=0);
	~EUserBlockPictures(){}
	static QMetaObject getMeta();
	Q_INVOKABLE EUserBlockPictures(const EUserBlockPictures &d) : QObject () { setData(d); }
	Q_INVOKABLE EUserBlockPictures &operator=(const EUserBlockPictures &d){ return setData(d); }
	Q_INVOKABLE bool operator== (const EUserBlockPictures &other) const{ if(equal(other))return true;return false;}
	Q_INVOKABLE inline bool operator!= (const EUserBlockPictures &other) const{ if(equal(other))return false;return true;}
	inline qint64 getId() const {return id;}
	void setId(qint64 d){id=d;}
	inline qint64 getUserID() const {return userID;}
	void setUserID(qint64 d){userID=d;}
	Q_INVOKABLE QString getName() const {return name;}
	void setName(const QString &d){name=d;}
	inline qint32 getVisibility() const {return visibility;}
	void setVisibility(qint32 d){visibility=d;}

protected:
	EUserBlockPictures &setData(const EUserBlockPictures &d){
		id=d.id;
		userID=d.userID;
		name=d.name;
		visibility=d.visibility;
		return *this;
	}
	bool equal(const EUserBlockPictures &other) const {
		if(id!=other.id)return false;
		if(userID!=other.userID)return false;
		if(name!=other.name)return false;
		if(visibility!=other.visibility)return false;
		return true;
	}
	qint64 id;
	qint64 userID;
	QString name;
	qint32 visibility;
};

Q_DECLARE_METATYPE(EUserBlockPictures)
Q_DECLARE_METATYPE(EUserBlockPictures*)
Q_DECLARE_METATYPE(QList<EUserBlockPictures*>)
Q_DECLARE_METATYPE(QList<EUserBlockPictures>)
#endif
