#ifndef EUSERBLOCK_H
#define EUSERBLOCK_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include "QStringList"
#include "QDateTime"
#include "QVariant"
#include "QObject"


/**
*@class EUserBlock
**/
class  EUserBlock : public QObject {
	Q_OBJECT
	Q_PROPERTY(qint64 id READ getId WRITE setId USER true)
	Q_PROPERTY(qint32 blockType READ getBlockType WRITE setBlockType USER true)
	Q_PROPERTY(QString name READ getName WRITE setName USER true)

public:
	Q_INVOKABLE EUserBlock(QObject *parent=0);
	~EUserBlock(){}
	static QMetaObject getMeta();
	Q_INVOKABLE EUserBlock(const EUserBlock &d) : QObject () { setData(d); }
	Q_INVOKABLE EUserBlock &operator=(const EUserBlock &d){ return setData(d); }
	Q_INVOKABLE bool operator== (const EUserBlock &other) const{ if(equal(other))return true;return false;}
	Q_INVOKABLE inline bool operator!= (const EUserBlock &other) const{ if(equal(other))return false;return true;}
	inline qint64 getId() const {return id;}
	void setId(qint64 d){id=d;}
	inline qint32 getBlockType() const {return blockType;}
	void setBlockType(qint32 d){blockType=d;}
	Q_INVOKABLE QString getName() const {return name;}
	void setName(const QString &d){name=d;}

protected:
	EUserBlock &setData(const EUserBlock &d){
		id=d.id;
		blockType=d.blockType;
		name=d.name;
		return *this;
	}
	bool equal(const EUserBlock &other) const {
		if(id!=other.id)return false;
		if(blockType!=other.blockType)return false;
		if(name!=other.name)return false;
		return true;
	}
	qint64 id;
	qint32 blockType;
	QString name;
};

Q_DECLARE_METATYPE(EUserBlock)
Q_DECLARE_METATYPE(EUserBlock*)
Q_DECLARE_METATYPE(QList<EUserBlock*>)
Q_DECLARE_METATYPE(QList<EUserBlock>)
#endif
