#ifndef EUSERPRODUCTCATEGORY_H
#define EUSERPRODUCTCATEGORY_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include "QStringList"
#include "QDateTime"
#include "QVariant"
#include "QObject"


/**
*@class EUserProductCategory
**/
class  EUserProductCategory : public QObject {
	Q_OBJECT
	Q_PROPERTY(qint64 id READ getId WRITE setId USER true)
	Q_PROPERTY(qint64 parentID READ getParentID WRITE setParentID USER true)
	Q_PROPERTY(qint64 userID READ getUserID WRITE setUserID USER true)
	Q_PROPERTY(QString name READ getName WRITE setName USER true)

public:
	Q_INVOKABLE EUserProductCategory(QObject *parent=0);
	~EUserProductCategory(){}
	static QMetaObject getMeta();
	Q_INVOKABLE EUserProductCategory(const EUserProductCategory &d) : QObject () { setData(d); }
	Q_INVOKABLE EUserProductCategory &operator=(const EUserProductCategory &d){ return setData(d); }
	Q_INVOKABLE bool operator== (const EUserProductCategory &other) const{ if(equal(other))return true;return false;}
	Q_INVOKABLE inline bool operator!= (const EUserProductCategory &other) const{ if(equal(other))return false;return true;}
	inline qint64 getId() const {return id;}
	void setId(qint64 d){id=d;}
	inline qint64 getParentID() const {return parentID;}
	void setParentID(qint64 d){parentID=d;}
	inline qint64 getUserID() const {return userID;}
	void setUserID(qint64 d){userID=d;}
	Q_INVOKABLE QString getName() const {return name;}
	void setName(const QString &d){name=d;}

protected:
	EUserProductCategory &setData(const EUserProductCategory &d){
		id=d.id;
		parentID=d.parentID;
		userID=d.userID;
		name=d.name;
		return *this;
	}
	bool equal(const EUserProductCategory &other) const {
		if(id!=other.id)return false;
		if(parentID!=other.parentID)return false;
		if(userID!=other.userID)return false;
		if(name!=other.name)return false;
		return true;
	}
	qint64 id;
	qint64 parentID;
	qint64 userID;
	QString name;
};

Q_DECLARE_METATYPE(EUserProductCategory)
Q_DECLARE_METATYPE(EUserProductCategory*)
Q_DECLARE_METATYPE(QList<EUserProductCategory*>)
Q_DECLARE_METATYPE(QList<EUserProductCategory>)
#endif
