#ifndef EUSERPRODUCTADDON_H
#define EUSERPRODUCTADDON_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include "QStringList"
#include "QDateTime"
#include "QVariant"
#include "QObject"


/**
*@class EUserProductAddon
**/
class  EUserProductAddon : public QObject {
	Q_OBJECT
	Q_PROPERTY(qint64 id READ getId WRITE setId USER true)
	Q_PROPERTY(qint64 productID READ getProductID WRITE setProductID USER true)
	Q_PROPERTY(QString name READ getName WRITE setName USER true)
	Q_PROPERTY(double price READ getPrice WRITE setPrice USER true)

public:
	Q_INVOKABLE EUserProductAddon(QObject *parent=0);
	~EUserProductAddon(){}
	static QMetaObject getMeta();
	Q_INVOKABLE EUserProductAddon(const EUserProductAddon &d) : QObject () { setData(d); }
	Q_INVOKABLE EUserProductAddon &operator=(const EUserProductAddon &d){ return setData(d); }
	Q_INVOKABLE bool operator== (const EUserProductAddon &other) const{ if(equal(other))return true;return false;}
	Q_INVOKABLE inline bool operator!= (const EUserProductAddon &other) const{ if(equal(other))return false;return true;}
	inline qint64 getId() const {return id;}
	void setId(qint64 d){id=d;}
	inline qint64 getProductID() const {return productID;}
	void setProductID(qint64 d){productID=d;}
	Q_INVOKABLE QString getName() const {return name;}
	void setName(const QString &d){name=d;}
	inline double getPrice() const {return price;}
	void setPrice(double d){price=d;}

protected:
	EUserProductAddon &setData(const EUserProductAddon &d){
		id=d.id;
		productID=d.productID;
		name=d.name;
		price=d.price;
		return *this;
	}
	bool equal(const EUserProductAddon &other) const {
		if(id!=other.id)return false;
		if(productID!=other.productID)return false;
		if(name!=other.name)return false;
		if(price!=other.price)return false;
		return true;
	}
	qint64 id;
	qint64 productID;
	QString name;
	double price;
};

Q_DECLARE_METATYPE(EUserProductAddon)
Q_DECLARE_METATYPE(EUserProductAddon*)
Q_DECLARE_METATYPE(QList<EUserProductAddon*>)
Q_DECLARE_METATYPE(QList<EUserProductAddon>)
#endif
