#ifndef EUSERORDERCONFIRMATION_H
#define EUSERORDERCONFIRMATION_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include "QStringList"
#include "QDateTime"
#include "QVariant"
#include "QObject"


/**
*@class EUserOrderConfirmation
**/
class  EUserOrderConfirmation : public QObject {
	Q_OBJECT
	Q_PROPERTY(qint64 userID READ getUserID WRITE setUserID USER true)
	Q_PROPERTY(qint64 buyerUserID READ getBuyerUserID WRITE setBuyerUserID USER true)
	Q_PROPERTY(QString note READ getNote WRITE setNote USER true)
	Q_PROPERTY(qint32 paymentType READ getPaymentType WRITE setPaymentType USER true)
	Q_PROPERTY(qint32 creditCardType READ getCreditCardType WRITE setCreditCardType USER true)
	Q_PROPERTY(qint32 isCollectAndDeliver READ getIsCollectAndDeliver WRITE setIsCollectAndDeliver USER true)
	Q_PROPERTY(QDate collectDate READ getCollectDate WRITE setCollectDate USER true)
	Q_PROPERTY(QDate deliveryDate READ getDeliveryDate WRITE setDeliveryDate USER true)
	Q_PROPERTY(qint32 collectPeriod READ getCollectPeriod WRITE setCollectPeriod USER true)
	Q_PROPERTY(qint32 deliveryPeriod READ getDeliveryPeriod WRITE setDeliveryPeriod USER true)

public:
	Q_INVOKABLE EUserOrderConfirmation(QObject *parent=0);
	~EUserOrderConfirmation(){}
	static QMetaObject getMeta();
	Q_INVOKABLE EUserOrderConfirmation(const EUserOrderConfirmation &d) : QObject () { setData(d); }
	Q_INVOKABLE EUserOrderConfirmation &operator=(const EUserOrderConfirmation &d){ return setData(d); }
	Q_INVOKABLE bool operator== (const EUserOrderConfirmation &other) const{ if(equal(other))return true;return false;}
	Q_INVOKABLE inline bool operator!= (const EUserOrderConfirmation &other) const{ if(equal(other))return false;return true;}
	inline qint64 getUserID() const {return userID;}
	void setUserID(qint64 d){userID=d;}
	inline qint64 getBuyerUserID() const {return buyerUserID;}
	void setBuyerUserID(qint64 d){buyerUserID=d;}
	Q_INVOKABLE QString getNote() const {return note;}
	void setNote(const QString &d){note=d;}
	inline qint32 getPaymentType() const {return paymentType;}
	void setPaymentType(qint32 d){paymentType=d;}
	inline qint32 getCreditCardType() const {return creditCardType;}
	void setCreditCardType(qint32 d){creditCardType=d;}
	inline qint32 getIsCollectAndDeliver() const {return isCollectAndDeliver;}
	void setIsCollectAndDeliver(qint32 d){isCollectAndDeliver=d;}
	Q_INVOKABLE QDate getCollectDate() const {return collectDate;}
	void setCollectDate(const QDate &d){collectDate=d;}
	Q_INVOKABLE QDate getDeliveryDate() const {return deliveryDate;}
	void setDeliveryDate(const QDate &d){deliveryDate=d;}
	inline qint32 getCollectPeriod() const {return collectPeriod;}
	void setCollectPeriod(qint32 d){collectPeriod=d;}
	inline qint32 getDeliveryPeriod() const {return deliveryPeriod;}
	void setDeliveryPeriod(qint32 d){deliveryPeriod=d;}

protected:
	EUserOrderConfirmation &setData(const EUserOrderConfirmation &d){
		userID=d.userID;
		buyerUserID=d.buyerUserID;
		note=d.note;
		paymentType=d.paymentType;
		creditCardType=d.creditCardType;
		isCollectAndDeliver=d.isCollectAndDeliver;
		collectDate=d.collectDate;
		deliveryDate=d.deliveryDate;
		collectPeriod=d.collectPeriod;
		deliveryPeriod=d.deliveryPeriod;
		return *this;
	}
	bool equal(const EUserOrderConfirmation &other) const {
		if(userID!=other.userID)return false;
		if(buyerUserID!=other.buyerUserID)return false;
		if(note!=other.note)return false;
		if(paymentType!=other.paymentType)return false;
		if(creditCardType!=other.creditCardType)return false;
		if(isCollectAndDeliver!=other.isCollectAndDeliver)return false;
		if(collectDate!=other.collectDate)return false;
		if(deliveryDate!=other.deliveryDate)return false;
		if(collectPeriod!=other.collectPeriod)return false;
		if(deliveryPeriod!=other.deliveryPeriod)return false;
		return true;
	}
	qint64 userID;
	qint64 buyerUserID;
	QString note;
	qint32 paymentType;
	qint32 creditCardType;
	qint32 isCollectAndDeliver;
	QDate collectDate;
	QDate deliveryDate;
	qint32 collectPeriod;
	qint32 deliveryPeriod;
};

Q_DECLARE_METATYPE(EUserOrderConfirmation)
Q_DECLARE_METATYPE(EUserOrderConfirmation*)
Q_DECLARE_METATYPE(QList<EUserOrderConfirmation*>)
Q_DECLARE_METATYPE(QList<EUserOrderConfirmation>)
#endif
