#ifndef EUSERBLOCKMENU_H
#define EUSERBLOCKMENU_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include "QStringList"
#include "QDateTime"
#include "QVariant"
#include "QObject"


/**
*@class EUserBlockMenu
**/
class  EUserBlockMenu : public QObject {
	Q_OBJECT
	Q_PROPERTY(qint64 id READ getId WRITE setId USER true)
	Q_PROPERTY(qint64 userID READ getUserID WRITE setUserID USER true)
	Q_PROPERTY(QString name READ getName WRITE setName USER true)

public:
	Q_INVOKABLE EUserBlockMenu(QObject *parent=0);
	~EUserBlockMenu(){}
	static QMetaObject getMeta();
	Q_INVOKABLE EUserBlockMenu(const EUserBlockMenu &d) : QObject () { setData(d); }
	Q_INVOKABLE EUserBlockMenu &operator=(const EUserBlockMenu &d){ return setData(d); }
	Q_INVOKABLE bool operator== (const EUserBlockMenu &other) const{ if(equal(other))return true;return false;}
	Q_INVOKABLE inline bool operator!= (const EUserBlockMenu &other) const{ if(equal(other))return false;return true;}
	inline qint64 getId() const {return id;}
	void setId(qint64 d){id=d;}
	inline qint64 getUserID() const {return userID;}
	void setUserID(qint64 d){userID=d;}
	Q_INVOKABLE QString getName() const {return name;}
	void setName(const QString &d){name=d;}

protected:
	EUserBlockMenu &setData(const EUserBlockMenu &d){
		id=d.id;
		userID=d.userID;
		name=d.name;
		return *this;
	}
	bool equal(const EUserBlockMenu &other) const {
		if(id!=other.id)return false;
		if(userID!=other.userID)return false;
		if(name!=other.name)return false;
		return true;
	}
	qint64 id;
	qint64 userID;
	QString name;
};

Q_DECLARE_METATYPE(EUserBlockMenu)
Q_DECLARE_METATYPE(EUserBlockMenu*)
Q_DECLARE_METATYPE(QList<EUserBlockMenu*>)
Q_DECLARE_METATYPE(QList<EUserBlockMenu>)
#endif
